/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Map;
import javax.swing.JFrame;

/**
 *
 * @author Matyena
 */
public class PantallaT20DHS extends javax.swing.JFrame {

    /**
     * Creates new form PantallaT20DHS
     */
    public PantallaT20DHS() {
        initComponents();
        
        //día actual
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
	LocalDate horaLocal = LocalDate.now();
        jLabel_DIA.setText("Precios de la electricidad hoy: " + dtf.format(horaLocal));
        
        //hora actual
        DateTimeFormatter hora = DateTimeFormatter.ofPattern("HH:mm:ss");
	LocalDateTime ahora = LocalDateTime.now();
        jLabel_HORA.setText("Consumo estimado en un 1h de uso a las " + hora.format(ahora));
        
        double consumoHorno = 0.88;
        double consumoLavadora = 1.142;
        double consumoNevera = 0.300;
        double consumoVitro = 2.2;
        double consumoTV = 0.1;
        double consumoOrdenador = 0.0635;
        
        String precioActual = APITarifa20DHSActual.getPrecioActual();
        precioActual = precioActual.replaceAll("[^\\.0123456789]",""); //le quito lo de kw/h
        double actual = Double.parseDouble(precioActual); //convierto el string en double
        
        //HORNO
        double totalHorno = actual * consumoHorno; //calculo el consumo total del horno
        double totalHorno2 = (double)Math.round(totalHorno * 1000d) / 1000d; //le quito decimales y lo dejo con 3
        String totalHorno3 = String.valueOf(totalHorno2); //convierto el double en String
        
        //LAVADORA
        double totalLavadora = actual * consumoLavadora;
        double totalLavadora2 = (double)Math.round(totalLavadora * 1000d) / 1000d;
        String totalLavadora3 = String.valueOf(totalLavadora2);
        
        //NEVERA
        double totalNevera = actual * consumoNevera;
        double totalNevera2 = (double)Math.round(totalNevera * 1000d) / 1000d;
        String totalNevera3 = String.valueOf(totalNevera2);
        
        //VITRO       
        double totalVitro = actual * consumoVitro;
        double totalVitro2 = (double)Math.round(totalVitro * 1000d) / 1000d;
        String totalVitro3 = String.valueOf(totalVitro2);
        
        //TELEVISION
        double totalTV = actual * consumoTV;
        double totalTV2 = (double)Math.round(totalTV * 1000d) / 1000d;
        String totalTV3 = String.valueOf(totalTV2);
        
        //ORDENADOR
        double totalOrdenador = actual * consumoOrdenador;
        double totalOrdenador2 = (double)Math.round(totalOrdenador * 1000d) / 1000d;
        String totalOrdenador3 = String.valueOf(totalOrdenador2);
        
        jLabel_HORNO.setText(totalHorno3 + " €");
        jLabel_LAVADORA.setText(totalLavadora3 + " €");
        jLabel_NEVERA.setText(totalNevera3 + " €");
        jLabel_VITRO.setText(totalVitro3 + " €");
        jLabel_TELEVISION.setText(totalTV3 + " €");
        jLabel_ORDENADOR.setText(totalOrdenador3 + " €");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel_DIA = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea_TARIFANORMAL = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel_PRECIOACTUAL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_PRECIOBAJO = new javax.swing.JLabel();
        jLabel_PRECIOALTO = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel_HORA = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel_HORNO = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel_VITRO = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel_LAVADORA = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel_NEVERA = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel_ORDENADOR = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel_TELEVISION = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_INICIO = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_T20A = new javax.swing.JMenuItem();
        jMenuItem_T20DHA = new javax.swing.JMenuItem();
        jMenuItem_T20DHS = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenu4.setText("jMenu4");

        jMenuItem4.setText("jMenuItem4");

        jMenu5.setText("jMenu5");

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 630));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 630));

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jLabel_DIA.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel_DIA.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_DIA.setText("Precio de la electricidad hoy: X");

        jTextArea_TARIFANORMAL.setBackground(new java.awt.Color(52, 73, 94));
        jTextArea_TARIFANORMAL.setColumns(20);
        jTextArea_TARIFANORMAL.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTextArea_TARIFANORMAL.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea_TARIFANORMAL.setRows(5);
        jTextArea_TARIFANORMAL.setAutoscrolls(false);
        jTextArea_TARIFANORMAL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jTextArea_TARIFANORMAL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane4.setViewportView(jTextArea_TARIFANORMAL);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Precio actual");

        jLabel_PRECIOACTUAL.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel_PRECIOACTUAL.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_PRECIOACTUAL.setText("Precio actual");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Precio más bajo del día");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Precio más alto del día");

        jLabel_PRECIOBAJO.setFont(new java.awt.Font("Lucida Grande", 1, 28)); // NOI18N
        jLabel_PRECIOBAJO.setForeground(new java.awt.Color(0, 204, 0));
        jLabel_PRECIOBAJO.setText("Precio bajo");

        jLabel_PRECIOALTO.setFont(new java.awt.Font("Lucida Grande", 1, 28)); // NOI18N
        jLabel_PRECIOALTO.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_PRECIOALTO.setText("Precio alto");

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tarifa 2.0DHS");

        jLabel_HORA.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel_HORA.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_HORA.setText("Consumo estimado en estos momentos (1h/uso)");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/horno32.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Horno:");

        jLabel_HORNO.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel_HORNO.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_HORNO.setText("Horno");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/vitro32.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Vitro:");

        jLabel_VITRO.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel_VITRO.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_VITRO.setText("Vitro");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/lavadora32.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Lavadora:");

        jLabel_LAVADORA.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel_LAVADORA.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_LAVADORA.setText("Lavadora");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/nevera32.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Nevera:");

        jLabel_NEVERA.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel_NEVERA.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NEVERA.setText("Nevera");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/ordenador32.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Ordenador:");

        jLabel_ORDENADOR.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel_ORDENADOR.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ORDENADOR.setText("Ordenador");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/television32.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("TV:");

        jLabel_TELEVISION.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel_TELEVISION.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TELEVISION.setText("Televisión");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jLabel_DIA)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel_PRECIOBAJO))
                                .addGap(75, 75, 75)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_PRECIOALTO)
                                    .addComponent(jLabel2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(jLabel_PRECIOACTUAL))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(266, 266, 266)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(237, 237, 237)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel10))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel_HORA))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel11)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel_HORNO))
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel13)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel_LAVADORA))))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(12, 12, 12)
                                                        .addComponent(jLabel12)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel_VITRO)))
                                                .addGap(76, 76, 76)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel9)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel15)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel_ORDENADOR))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel16)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel18)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel_TELEVISION))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(jLabel6)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel14)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel_NEVERA)))))))))))
                .addContainerGap(324, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel_DIA)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_PRECIOACTUAL)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_PRECIOBAJO)
                            .addComponent(jLabel_PRECIOALTO))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_HORA, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel_NEVERA)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel_ORDENADOR)
                                            .addComponent(jLabel15)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel_TELEVISION)
                                        .addComponent(jLabel18))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel_HORNO)
                                            .addComponent(jLabel11))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel_VITRO)
                                            .addComponent(jLabel12))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel_LAVADORA)
                                        .addComponent(jLabel13))))))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jMenu_INICIO.setText("Inicio");
        jMenu_INICIO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_INICIOMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_INICIO);

        jMenu2.setText("Tarifas");

        jMenuItem_T20A.setText("Tarifa 2.0 A");
        jMenuItem_T20A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_T20AActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_T20A);

        jMenuItem_T20DHA.setText("Tarifa 2.0 DHA\t");
        jMenuItem_T20DHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_T20DHAActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_T20DHA);

        jMenuItem_T20DHS.setText("Tarifa 2.0 DHS\t");
        jMenuItem_T20DHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_T20DHSActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_T20DHS);

        jMenuBar1.add(jMenu2);

        jMenu7.setText("Ayuda");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Map<String,String> res = APITarifa20DHS.getPrecioyFecha();

        if (res != null) {
            this.jTextArea_TARIFANORMAL.setText(res.get("result"));
            this.jLabel_PRECIOBAJO.setText(res.get("min"));
            this.jLabel_PRECIOALTO.setText(res.get("max"));
        } else {
            this.jTextArea_TARIFANORMAL.setText("");
            this.jLabel_PRECIOBAJO.setText("Precio más bajo: ");
            this.jLabel_PRECIOALTO.setText("Precio más alto: ");
        }

        jLabel_PRECIOACTUAL.setText(APITarifa20DHSActual.getPrecioActual());

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem_T20AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_T20AActionPerformed
        PantallaT20A pantallat20a = new PantallaT20A();
        pantallat20a.setVisible(true);
        pantallat20a.pack();
        pantallat20a.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jMenuItem_T20AActionPerformed

    private void jMenuItem_T20DHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_T20DHAActionPerformed
        PantallaT20DHA pantallat20dha = new PantallaT20DHA();
        pantallat20dha.setVisible(true);
        pantallat20dha.pack();
        pantallat20dha.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jMenuItem_T20DHAActionPerformed

    private void jMenuItem_T20DHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_T20DHSActionPerformed
        PantallaT20DHS pantallat20dhs = new PantallaT20DHS();
        pantallat20dhs.setVisible(true);
        pantallat20dhs.pack();
        pantallat20dhs.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jMenuItem_T20DHSActionPerformed

    private void jMenu_INICIOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_INICIOMouseClicked
        PantallaInicio inicio = new PantallaInicio();
        inicio.setVisible(true);
        inicio.pack();
        inicio.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jMenu_INICIOMouseClicked

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
        PantallaAyuda ayuda = new PantallaAyuda();
        ayuda.setVisible(true);
        ayuda.pack();
        ayuda.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jMenu7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaT20DHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaT20DHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaT20DHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaT20DHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaT20DHS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_DIA;
    private javax.swing.JLabel jLabel_HORA;
    private javax.swing.JLabel jLabel_HORNO;
    private javax.swing.JLabel jLabel_LAVADORA;
    private javax.swing.JLabel jLabel_NEVERA;
    private javax.swing.JLabel jLabel_ORDENADOR;
    private javax.swing.JLabel jLabel_PRECIOACTUAL;
    private javax.swing.JLabel jLabel_PRECIOALTO;
    private javax.swing.JLabel jLabel_PRECIOBAJO;
    private javax.swing.JLabel jLabel_TELEVISION;
    private javax.swing.JLabel jLabel_VITRO;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem_T20A;
    private javax.swing.JMenuItem jMenuItem_T20DHA;
    private javax.swing.JMenuItem jMenuItem_T20DHS;
    private javax.swing.JMenu jMenu_INICIO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea_TARIFANORMAL;
    // End of variables declaration//GEN-END:variables
}
