/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author Matyena
 */
public class PantallaInicio extends javax.swing.JFrame {

    /**
     * Creates new form PantallaInicio2
     */
    public PantallaInicio() {
        initComponents();
        
        jLabel_PREGUNTA.setText("¿Qué tarifa tienes contratada?");
        jLabel_GENERAL.setText("GENERAL (2.0A)");
        jLabel_DISCRIMINACION.setText("DOS PERIODOS (2.0DHA)");
        jLabel_VEHICULO.setText("VEHÍCULO ELÉCTRICO (2.0DHS)");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_PREGUNTA = new javax.swing.JLabel();
        jLabel_T20A = new javax.swing.JLabel();
        jLabel_T20DHS = new javax.swing.JLabel();
        jLabel_T20DHA = new javax.swing.JLabel();
        jLabel_GENERAL = new javax.swing.JLabel();
        jLabel_DISCRIMINACION = new javax.swing.JLabel();
        jLabel_VEHICULO = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_INICIO = new javax.swing.JMenu();
        jMenu_PantallaAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 550));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jLabel_PREGUNTA.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel_PREGUNTA.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_PREGUNTA.setText("¿Qué tarifa tienes contratada?");

        jLabel_T20A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/20A.png"))); // NOI18N
        jLabel_T20A.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_T20A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_T20AMouseClicked(evt);
            }
        });

        jLabel_T20DHS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/20DHS.png"))); // NOI18N
        jLabel_T20DHS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_T20DHS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_T20DHSMouseClicked(evt);
            }
        });

        jLabel_T20DHA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/20DHA.png"))); // NOI18N
        jLabel_T20DHA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_T20DHA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_T20DHAMouseClicked(evt);
            }
        });

        jLabel_GENERAL.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel_GENERAL.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_GENERAL.setText("GENERAL (2.0A)");

        jLabel_DISCRIMINACION.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel_DISCRIMINACION.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_DISCRIMINACION.setText("DOS PERIODOS (2.0 DHA)");

        jLabel_VEHICULO.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel_VEHICULO.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_VEHICULO.setText("VEHÍCULO ELÉCTRICO (2.0DHS)");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("No sé qué tarifa tengo");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_T20A, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel_GENERAL)))
                .addGap(109, 109, 109)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_T20DHA)
                        .addGap(102, 102, 102)
                        .addComponent(jLabel_T20DHS))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_DISCRIMINACION)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(jLabel_VEHICULO)))
                .addGap(79, 79, 79))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel_PREGUNTA))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(415, 415, 415)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel_PREGUNTA)
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_GENERAL)
                    .addComponent(jLabel_DISCRIMINACION)
                    .addComponent(jLabel_VEHICULO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_T20A, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_T20DHA)
                    .addComponent(jLabel_T20DHS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(57, 57, 57))
        );

        jMenu_INICIO.setText("Inicio");
        jMenu_INICIO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_INICIOMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_INICIO);

        jMenu_PantallaAyuda.setText("Ayuda");
        jMenu_PantallaAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_PantallaAyudaMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_PantallaAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_INICIOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_INICIOMouseClicked
        
    }//GEN-LAST:event_jMenu_INICIOMouseClicked

    private void jLabel_T20AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_T20AMouseClicked
        PantallaT20A pantallat20a = new PantallaT20A();
        pantallat20a.setVisible(true);
        pantallat20a.pack();
        pantallat20a.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel_T20AMouseClicked

    private void jLabel_T20DHAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_T20DHAMouseClicked
        PantallaT20DHA pantallat20dha = new PantallaT20DHA();
        pantallat20dha.setVisible(true);
        pantallat20dha.pack();
        pantallat20dha.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel_T20DHAMouseClicked

    private void jLabel_T20DHSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_T20DHSMouseClicked
        PantallaT20DHS pantallat20dhs = new PantallaT20DHS();
        pantallat20dhs.setVisible(true);
        pantallat20dhs.pack();
        pantallat20dhs.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel_T20DHSMouseClicked

    private void jMenu_PantallaAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_PantallaAyudaMouseClicked
        PantallaAyuda ayuda = new PantallaAyuda();
        ayuda.setVisible(true);
        ayuda.pack();
        ayuda.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jMenu_PantallaAyudaMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        PantallaT20A pantallat20a = new PantallaT20A();
        pantallat20a.setVisible(true);
        pantallat20a.pack();
        pantallat20a.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_DISCRIMINACION;
    private javax.swing.JLabel jLabel_GENERAL;
    private javax.swing.JLabel jLabel_PREGUNTA;
    private javax.swing.JLabel jLabel_T20A;
    private javax.swing.JLabel jLabel_T20DHA;
    private javax.swing.JLabel jLabel_T20DHS;
    private javax.swing.JLabel jLabel_VEHICULO;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_INICIO;
    private javax.swing.JMenu jMenu_PantallaAyuda;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
