/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Map;
import javax.swing.JFrame;

/**
 *
 * @author Cristian Plasencia
 */

public class PantallaT20A extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    
    public PantallaT20A() {
        initComponents();
        
        double consumoHorno = 0.88;
        double consumoLavadora = 1.142;
        double consumoNevera = 0.300;
        double consumoVitro = 2.2;
        double consumoTV = 0.1;
        double consumoOrdenador = 0.0635;
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
	LocalDate horaLocal = LocalDate.now();
        jLabel_DIA.setText("Precios de la electricidad hoy: " + dtf.format(horaLocal));
        
        DateTimeFormatter hora = DateTimeFormatter.ofPattern("HH:mm:ss");
	LocalDateTime ahora = LocalDateTime.now();
        jLabel_HORA.setText("Consumo estimado en un 1h de uso a las " + hora.format(ahora));
        
        
        
        String precioActual = APITarifa20AActual.getPrecioActual();
        precioActual = precioActual.replaceAll("[^\\.0123456789]",""); //le quito lo de kw/h
        double actual = Double.parseDouble(precioActual); //convierto el string en double
        
        //HORNO
        double totalHorno = actual * consumoHorno; //calculo el consumo total del horno
        double totalHorno2 = (double)Math.round(totalHorno * 1000d) / 1000d; //le quito decimales y lo dejo con 3
        String totalHorno3 = String.valueOf(totalHorno2); //convierto el double en String
        
        //LAVADORA
        double totalLavadora = actual * consumoLavadora;
        double totalLavadora2 = (double)Math.round(totalLavadora * 1000d) / 1000d;
        String totalLavadora3 = String.valueOf(totalLavadora2);
        
        //NEVERA
        double totalNevera = actual * consumoNevera;
        double totalNevera2 = (double)Math.round(totalNevera * 1000d) / 1000d;
        String totalNevera3 = String.valueOf(totalNevera2);
        
        //VITRO       
        double totalVitro = actual * consumoVitro;
        double totalVitro2 = (double)Math.round(totalVitro * 1000d) / 1000d;
        String totalVitro3 = String.valueOf(totalVitro2);
        
        //TELEVISION
        double totalTV = actual * consumoTV;
        double totalTV2 = (double)Math.round(totalTV * 1000d) / 1000d;
        String totalTV3 = String.valueOf(totalTV2);
        
        //ORDENADOR
        double totalOrdenador = actual * consumoOrdenador;
        double totalOrdenador2 = (double)Math.round(totalOrdenador * 1000d) / 1000d;
        String totalOrdenador3 = String.valueOf(totalOrdenador2);
        
        jLabel_HORNO.setText(totalHorno3 + " €");
        jLabel_LAVADORA.setText(totalLavadora3 + " €");
        jLabel_NEVERA.setText(totalNevera3 + " €");
        jLabel_VITRO.setText(totalVitro3 + " €");
        jLabel_TELEVISION.setText(totalTV3 + " €");
        jLabel_ORDENADOR.setText(totalOrdenador3 + " €");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel5 = new javax.swing.JPanel();
        jLabel_PRECIOALTO = new javax.swing.JLabel();
        jLabel_PRECIOBAJO = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_PRECIOACTUAL = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea_TARIFANORMAL = new javax.swing.JTextArea();
        jLabel_DIA = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_HORNO = new javax.swing.JLabel();
        jLabel_VITRO = new javax.swing.JLabel();
        jLabel_LAVADORA = new javax.swing.JLabel();
        jLabel_NEVERA = new javax.swing.JLabel();
        jLabel_ORDENADOR = new javax.swing.JLabel();
        jLabel_TELEVISION = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel_HORA = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_INICIO = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_TarifaNormal = new javax.swing.JMenuItem();
        jMenuItem_TarifaDiscriminacionHoraria = new javax.swing.JMenuItem();
        jMenuItem_TarifaVehiculoElectrico = new javax.swing.JMenuItem();
        jMenu_PantallaAyuda = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 630));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 630));
        getContentPane().setLayout(null);

        jPanel5.setBackground(new java.awt.Color(44, 62, 80));

        jLabel_PRECIOALTO.setFont(new java.awt.Font("Lucida Grande", 1, 28)); // NOI18N
        jLabel_PRECIOALTO.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_PRECIOALTO.setText("Precio alto");

        jLabel_PRECIOBAJO.setFont(new java.awt.Font("Lucida Grande", 1, 28)); // NOI18N
        jLabel_PRECIOBAJO.setForeground(new java.awt.Color(0, 204, 0));
        jLabel_PRECIOBAJO.setText("Precio bajo");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Precio más bajo del día");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Precio más alto del día");

        jLabel_PRECIOACTUAL.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel_PRECIOACTUAL.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_PRECIOACTUAL.setText("Precio actual");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Precio actual");

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea_TARIFANORMAL.setBackground(new java.awt.Color(52, 73, 94));
        jTextArea_TARIFANORMAL.setColumns(20);
        jTextArea_TARIFANORMAL.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTextArea_TARIFANORMAL.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea_TARIFANORMAL.setRows(5);
        jTextArea_TARIFANORMAL.setAutoscrolls(false);
        jTextArea_TARIFANORMAL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jTextArea_TARIFANORMAL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane4.setViewportView(jTextArea_TARIFANORMAL);

        jLabel_DIA.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel_DIA.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_DIA.setText("Precio de la electricidad hoy: X");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tarifa 2.0 A");

        jLabel_HORNO.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel_HORNO.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_HORNO.setText("Horno");

        jLabel_VITRO.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel_VITRO.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_VITRO.setText("Vitro");

        jLabel_LAVADORA.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel_LAVADORA.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_LAVADORA.setText("Lavadora");

        jLabel_NEVERA.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel_NEVERA.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NEVERA.setText("Nevera");

        jLabel_ORDENADOR.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel_ORDENADOR.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ORDENADOR.setText("Ordenador");

        jLabel_TELEVISION.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel_TELEVISION.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TELEVISION.setText("Televisión");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/nevera32.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/television32.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/vitro32.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/ordenador32.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/horno32.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/lavadora32.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Horno:");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Vitro:");

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Lavadora:");

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Nevera:");

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Ordenador:");

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("TV:");

        jLabel_HORA.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel_HORA.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_HORA.setText("Consumo estimado en estos momentos (1h/uso)");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel_PRECIOBAJO)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                            .addGap(39, 39, 39)
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel_VITRO))))
                                .addGap(87, 87, 87)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_PRECIOALTO)
                                    .addComponent(jLabel2)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(jLabel_PRECIOACTUAL))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(jLabel3))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(jLabel4))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_HORA)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addComponent(jLabel11)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel_HORNO))
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addComponent(jLabel13)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel_LAVADORA)))
                                                .addGap(76, 76, 76)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addComponent(jLabel9)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel15)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel_ORDENADOR))
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addComponent(jLabel6)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel16)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel_TELEVISION))
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(jLabel5)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel14)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel_NEVERA))))))))))
                    .addComponent(jLabel_DIA))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel_DIA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_PRECIOACTUAL)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_PRECIOBAJO)
                            .addComponent(jLabel_PRECIOALTO))
                        .addGap(54, 54, 54)
                        .addComponent(jLabel_HORA, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel_NEVERA)))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel_ORDENADOR)
                                            .addComponent(jLabel15)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel_TELEVISION)
                                        .addComponent(jLabel16))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel_HORNO)
                                            .addComponent(jLabel11))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel_VITRO)
                                            .addComponent(jLabel12))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel_LAVADORA)
                                        .addComponent(jLabel13))))))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton2)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 1010, 610);

        jMenu_INICIO.setText("Inicio");
        jMenu_INICIO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_INICIOMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_INICIO);

        jMenu2.setText("Tarifas");

        jMenuItem_TarifaNormal.setText("Tarifa 2.0 A");
        jMenuItem_TarifaNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_TarifaNormalActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_TarifaNormal);

        jMenuItem_TarifaDiscriminacionHoraria.setText("Tarifa 2.0 DHA");
        jMenuItem_TarifaDiscriminacionHoraria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_TarifaDiscriminacionHorariaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_TarifaDiscriminacionHoraria);

        jMenuItem_TarifaVehiculoElectrico.setText("Tarifa 2.0 DHS");
        jMenuItem_TarifaVehiculoElectrico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_TarifaVehiculoElectricoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_TarifaVehiculoElectrico);

        jMenuBar1.add(jMenu2);

        jMenu_PantallaAyuda.setText("Ayuda");
        jMenu_PantallaAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_PantallaAyudaMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_PantallaAyuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Map<String,String> res = APITarifa20A.getPrecioyHoras();
        
        if (res != null) {
            this.jTextArea_TARIFANORMAL.setText(res.get("result"));
            this.jLabel_PRECIOBAJO.setText(res.get("min"));
            this.jLabel_PRECIOALTO.setText(res.get("max"));
        } else {
            this.jTextArea_TARIFANORMAL.setText("");
            this.jLabel_PRECIOBAJO.setText("Precio más bajo: ");
            this.jLabel_PRECIOALTO.setText("Precio más alto: ");
        }
        
        jLabel_PRECIOACTUAL.setText(APITarifa20AActual.getPrecioActual());
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem_TarifaDiscriminacionHorariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_TarifaDiscriminacionHorariaActionPerformed
        PantallaT20DHA pantallat20dha = new PantallaT20DHA();
        pantallat20dha.setVisible(true);
        pantallat20dha.pack();
        pantallat20dha.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jMenuItem_TarifaDiscriminacionHorariaActionPerformed

    private void jMenuItem_TarifaVehiculoElectricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_TarifaVehiculoElectricoActionPerformed
        PantallaT20DHS pantallat20dhs = new PantallaT20DHS();
        pantallat20dhs.setVisible(true);
        pantallat20dhs.pack();
        pantallat20dhs.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jMenuItem_TarifaVehiculoElectricoActionPerformed

    private void jMenuItem_TarifaNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_TarifaNormalActionPerformed
        PantallaT20A pantallat20a = new PantallaT20A();
        pantallat20a.setVisible(true);
        pantallat20a.pack();
        pantallat20a.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jMenuItem_TarifaNormalActionPerformed

    private void jMenu_INICIOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_INICIOMouseClicked
        PantallaInicio inicio = new PantallaInicio();
        inicio.setVisible(true);
        inicio.pack();
        inicio.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jMenu_INICIOMouseClicked

    private void jMenu_PantallaAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_PantallaAyudaMouseClicked
        PantallaAyuda ayuda = new PantallaAyuda();
        ayuda.setVisible(true);
        ayuda.pack();
        ayuda.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jMenu_PantallaAyudaMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaT20A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaT20A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaT20A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaT20A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaT20A().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_DIA;
    private javax.swing.JLabel jLabel_HORA;
    private javax.swing.JLabel jLabel_HORNO;
    private javax.swing.JLabel jLabel_LAVADORA;
    private javax.swing.JLabel jLabel_NEVERA;
    private javax.swing.JLabel jLabel_ORDENADOR;
    private javax.swing.JLabel jLabel_PRECIOACTUAL;
    private javax.swing.JLabel jLabel_PRECIOALTO;
    private javax.swing.JLabel jLabel_PRECIOBAJO;
    private javax.swing.JLabel jLabel_TELEVISION;
    private javax.swing.JLabel jLabel_VITRO;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem_TarifaDiscriminacionHoraria;
    private javax.swing.JMenuItem jMenuItem_TarifaNormal;
    private javax.swing.JMenuItem jMenuItem_TarifaVehiculoElectrico;
    private javax.swing.JMenu jMenu_INICIO;
    private javax.swing.JMenu jMenu_PantallaAyuda;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea_TARIFANORMAL;
    // End of variables declaration//GEN-END:variables
}
